use std::sync::{
    Arc,
    atomic::{AtomicUsize, Ordering},
};

use iced::{
    Alignment::Center,
    Element, Length, Task,
    widget::{self, Text, button, space},
};
use url::Url;

use backend::api::{
    endpoint_api::{
        EndpointKind,
        EndpointType::{self, Jellyfin},
        UserPasswordAuth,
    },
    jellyfin::{api::JellyfinApi, errors::ApiError},
};

use crate::ui::{Receiver, components::icons};

/// The settings for an endpoint
#[derive(Clone)]
pub struct EndpointSettings {
    pub id: usize,
    /// Is this endpoint card expanded
    pub expanded: bool,
    /// Is this endpoint selected
    pub selected: bool,
    /// Should this endpoint be indexed
    pub index: bool,
    /// The name of this endpoint
    pub name: String,
    /// The type of this endpoint
    pub endpoint_type: Option<EndpointType>,
    /// The actual endpoint generated by testing
    /// This can be used at the upper point to synchronize endpoints
    pub endpoint: Option<EndpointKind>,
    /// The url (if it has one) of this Endpoint
    pub url: String,
    /// The username (if it has one) of this Endpoint
    pub username: String,
    /// The password (if it has one) of this Endpoint
    pub password: String,
    /// [`None`] if the endpoint has been tested successfully \
    /// Otherwise contains an error that describes the failure
    pub error: Option<Error>,
}

static ENDPOINT_COUNTER: AtomicUsize = AtomicUsize::new(0);

impl Default for EndpointSettings {
    fn default() -> Self {
        Self {
            id: ENDPOINT_COUNTER.fetch_add(1, Ordering::Relaxed),
            expanded: true,
            selected: false,
            index: false,
            name: "New endpoint".to_string(),
            endpoint_type: None,
            endpoint: None,
            url: String::new(),
            username: String::new(),
            password: String::new(),
            error: None,
        }
    }
}

pub type EndpointMsg = Cmd;

#[derive(Clone, Debug)]
pub enum Cmd {
    ToggleExpand,
    ToggleSelected(bool),
    ToggleIndexing(bool),
    ChooseEndpoint(EndpointType),
    ChangeName(String),
    ChangeUrl(String),
    ChangeUsername(String),
    ChangePassword(String),
    TestEndpoint,
    TestResult(Result<EndpointKind, Error>),
    RemoveSelf,
}

const SCROLL_DOWN_ICON: char = '\u{e803}';
const SCROLL_RIGHT_ICON: char = '\u{e805}';

impl EndpointSettings {
    pub fn view(&self) -> Element<'_, EndpointMsg> {
        const HEADER_TEXT_SIZE: u32 = 18;
        const HEADER_CONTROL_SIZE: u32 = 22;

        // Always visible
        let header_row = widget::row([
            // Checkbox for endpoint selection
            widget::checkbox(self.selected)
                .on_toggle_maybe(self.endpoint.as_ref().map(|_| |b| Cmd::ToggleSelected(b)))
                .text_size(HEADER_CONTROL_SIZE)
                .into(),
            // The endpoint icon
            self.icon().size(HEADER_CONTROL_SIZE).into(),
            // The endpoint name
            widget::text(self.name.clone())
                .size(HEADER_TEXT_SIZE)
                .into(),
            widget::space().width(Length::Fill).into(),
            widget::button(if self.expanded {
                widget::text!("{}", SCROLL_DOWN_ICON).font("Iced-Icons")
            } else {
                widget::text!("{}", SCROLL_RIGHT_ICON).font("Iced-Icons")
            })
            .on_press(Cmd::ToggleExpand)
            .into(),
        ])
        .spacing(6)
        .align_y(Center);

        // Lets the user choose the name
        let name_row = widget::row([
            widget::text("Name").width(Length::FillPortion(1)).into(),
            widget::text_input("Name", &self.name)
                .on_input(Cmd::ChangeName)
                .width(Length::FillPortion(2))
                .into(),
        ])
        .align_y(Center);

        // Lets the user choose the type
        let selection_row = widget::row([
            widget::text("Type").width(Length::FillPortion(1)).into(),
            widget::pick_list(
                self.endpoint_type.clone(),
                EndpointType::ALL,
                EndpointType::to_string,
            )
            .on_select(Cmd::ChooseEndpoint)
            .width(Length::FillPortion(2))
            .into(),
        ])
        .align_y(Center);

        // Lets the user choose the url
        let url_row = widget::row([
            widget::text("Url").width(Length::FillPortion(1)).into(),
            widget::text_input("Url", &self.url)
                .on_input(Cmd::ChangeUrl)
                .width(Length::FillPortion(2))
                .into(),
        ])
        .align_y(Center);

        // Lets the user choose the type
        let user_row = widget::row([
            widget::text("Username")
                .width(Length::FillPortion(1))
                .into(),
            widget::text_input("Username", &self.username)
                .on_input(Cmd::ChangeUsername)
                .width(Length::FillPortion(2))
                .into(),
        ])
        .align_y(Center);

        // Lets the user choose the type
        let password_row = widget::row([
            widget::text("Password")
                .width(Length::FillPortion(1))
                .into(),
            widget::text_input(
                "Password",
                // Mask password
                &self.password,
            )
            .secure(true)
            .on_input(Cmd::ChangePassword)
            .width(Length::FillPortion(2))
            .into(),
        ])
        .align_y(Center);

        // Lets the user activate indexing for this endpoint
        let index_row = widget::row([
            widget::text("Activate indexing")
                .width(Length::FillPortion(1))
                .into(),
            widget::checkbox(self.index)
                .on_toggle(Cmd::ToggleIndexing)
                .width(Length::FillPortion(2))
                .into(),
        ]);

        // Displays a text if something goes wrong
        let test_error_text = widget::text(if let Some(ref e) = self.error {
            e.to_string()
        } else if self.endpoint.is_some() {
            "Endpoint is working!".to_string()
        } else {
            String::new()
        })
        .style(|t| {
            if self.error.is_some() {
                widget::text::danger(t)
            } else {
                widget::text::success(t)
            }
        });

        // Lets the user test and save
        let test_save_row = widget::row([
            widget::button("Test")
                .on_press_maybe(self.endpoint_type.is_some().then_some(Cmd::TestEndpoint))
                .into(),
            test_error_text.into(),
            space().width(Length::Fill).into(),
            widget::button(icons::trash())
                .style(button::danger)
                .on_press(Cmd::RemoveSelf)
                .into(),
        ])
        .spacing(6)
        .align_y(Center);

        let mut column = widget::column([header_row.into()]).spacing(6);
        if self.expanded {
            column = column.extend([
                widget::rule::horizontal(2).into(),
                name_row.into(),
                selection_row.into(),
            ]);

            // Endpoints requiring a URL
            if matches!(self.endpoint_type, Some(Jellyfin)) {
                column = column.push(url_row);
            }

            // Endpoints require user password
            if matches!(self.endpoint_type, Some(Jellyfin)) {
                column = column.extend([user_row.into(), password_row.into()]);
            }

            column = column.extend([index_row.into(), test_save_row.into()]);
        }

        widget::container(column)
            .style(widget::container::rounded_box)
            .padding(6)
            .into()
    }

    pub fn update(&mut self, msg: impl Into<EndpointMsg>) -> Task<EndpointMsg> {
        match msg.into() {
            Cmd::ToggleExpand => {
                self.expanded = !self.expanded;
                Task::none()
            }
            Cmd::ToggleSelected(selected) => {
                self.selected = selected;
                // Signal the upper settings to apply changes to the endpoints
                super::Settings::send(super::SettingsMsg::SyncEndpoints);
                Task::none()
            }
            Cmd::ToggleIndexing(index) => {
                self.index = index;
                // Signal the upper settings to apply changes to the endpoints
                super::Settings::send(super::SettingsMsg::SyncEndpoints);
                Task::none()
            }
            Cmd::ChangeName(name) => {
                self.name = name;
                Task::none()
            }
            Cmd::ChooseEndpoint(endpoint) => {
                self.endpoint_type = Some(endpoint);
                self.endpoint = None;
                self.error = None;
                Task::none()
            }
            Cmd::ChangeUrl(url) => {
                self.url = url;
                self.endpoint = None;
                self.error = None;
                Task::none()
            }
            Cmd::ChangeUsername(user) => {
                self.username = user;
                self.endpoint = None;
                self.error = None;
                Task::none()
            }
            Cmd::ChangePassword(password) => {
                self.password = password;
                self.endpoint = None;
                self.error = None;
                Task::none()
            }
            Cmd::TestEndpoint => match self.endpoint_type {
                Some(EndpointType::Jellyfin) => {
                    let url = self.url.clone();
                    let username = self.username.clone();
                    let password = self.password.clone();
                    let indexing = self.index;

                    Task::perform(
                        (async move || {
                            let jf = JellyfinApi::auth_user_password(
                                Url::parse(&url)?,
                                username,
                                password,
                            )
                            .await?;

                            Ok(EndpointKind::Indexable {
                                indexing,
                                endpoint: Arc::new(jf),
                            })
                        })(),
                        Cmd::TestResult,
                    )
                }
                None => {
                    // shouldn't even be possible in the first place
                    self.error = Some(Error::NoEndpointError);
                    Task::none()
                }
            },
            Cmd::TestResult(res) => {
                match res {
                    Ok(api) => self.endpoint = Some(api),
                    Err(e) => self.error = Some(e),
                }
                Task::none()
            }
            Cmd::RemoveSelf => {
                super::Settings::send(super::SettingsMsg::RemoveEndpoint(self.id));
                Task::none()
            }
        }
    }

    pub fn icon(&self) -> Text<'_> {
        match self.endpoint_type {
            // TODO: proper icon
            None => icons::tag(),
            Some(EndpointType::Jellyfin) => icons::jellyfin(),
        }
    }
}

#[derive(Debug, thiserror::Error, Clone)]
pub enum Error {
    #[error("You need to select an endpoint")]
    NoEndpointError,
    #[error("Invalid URL: {0}")]
    UrlError(#[from] url::ParseError),
    #[error("Unauthorized: Check username & password")]
    Unauthorized,
    #[error("{0}")]
    Unknown(ApiError),
}

impl From<ApiError> for Error {
    fn from(value: ApiError) -> Self {
        match value {
            ApiError::Unauthorized => Error::Unauthorized,
            _ => Error::Unknown(value),
        }
    }
}
