use std::{fs, path::PathBuf};

use serde::Deserialize;

fn main() {
    // Generate icon definitions
    generate_icons();
}

const ICONS_PATH: &str = "src/ui/components/icons/leidenfrost.icomoon.json";
const OUT_DIR: &str = "src/ui/components/";
const FONT_NAME: &str = "leidenfrost";

/// The icomoon icons container
#[derive(Deserialize)]
struct Icomoon {
    glyphs: Vec<Glyph>,
}

/// A font glyph definition
#[derive(Deserialize)]
struct Glyph {
    extras: Extras,
}

/// Additional glyph properties
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Extras {
    /// The name of the icon
    name: String,
    /// The unicode code point of the icon
    code_point: u32,
}

/// Generates an iced component for every icon in the ico moon file
fn generate_icons() {
    println!("cargo:rerun-if-changed={ICONS_PATH}");

    let json = fs::read_to_string(ICONS_PATH).unwrap();
    let icomoon: Icomoon = serde_json::from_str(&json).unwrap();

    let out_dir = PathBuf::from(OUT_DIR);
    let dest = out_dir.join("icons.rs");

    let mut generated = String::new();
    generated.push_str("// Auto-generated by build.rs");
    generated.push_str(
        "
use iced::{
    Font,
    advanced::text,
    widget::{self, Text, text::Catalog},
};\n",
    );

    for glyph in icomoon.glyphs {
        let fun = glyph_function(glyph.extras);
        generated.push_str(&fun);
    }

    fs::write(dest, generated).unwrap();
}

fn glyph_function(extras: Extras) -> String {
    let fn_name = sanitize(&extras.name);
    let char: char = std::char::from_u32(extras.code_point).unwrap();

    format!(
        r#"
pub fn {fn_name}<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {{
    widget::text({char:?}).font("{FONT_NAME}")
}}
"#
    )
}

/// Sanitize the icon names into function identifiers
fn sanitize(name: &str) -> String {
    let mut s = String::new();

    for c in name.chars() {
        let clean_char = match c {
            'a'..='z' | 'A'..='Z' => &c.to_string().to_lowercase(),
            '0' => "zero",
            '1' => "one",
            '2' => "two",
            '3' => "three",
            '4' => "four",
            '5' => "five",
            '6' => "six",
            '7' => "seven",
            '8' => "eight",
            '9' => "nine",
            _ => "_",
        };

        s.push_str(clean_char);
    }

    s
}
