[package]
name = "randale_iced"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.32"
iced = { version = "0.14.0", features = ["image"] }
iced_fonts = { version = "0.3.0", features = ["lucide"] }
libmpv2 = "5.0.3"
tokio = { version = "1.50.0", features = ["macros", "test-util"] }
# jellyfin API
jellyfin = { path = "./jellyfin" }
serde = { version = "1.0.228", features = ["derive"] }
