[package]
name = "leidenfrost"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { path = "../iced", features = ["image", "sipper", "tokio", "advanced"] }
libmpv2 = "5.0.3"
tokio = { version = "1.50.0", features = ["rt"] }
tokio-stream = { version = "0.1.18", features = ["sync"] }
serde = { version = "1.0.228", features = ["derive"] }
# https://docs.rs/serde_json_path_to_error
serde_json = { package = "serde_json_path_to_error", version = "0.1.5" }
chrono = { version = "0.4.44", features = ["serde"] }
url = { version = "2.5.8", features = ["serde"] }
thiserror = "2.0.18"
color-eyre = "0.6.5"
reqwest = { version = "0.13.2", features = ["json", "query"] }
http-serde = "2.1.1"
blurhash = "0.2.3"
bytes = "1.11.1"
sea-orm = { version = "2.0.0-rc.41", features = [
    "sqlx-sqlite",
    "runtime-tokio",
    "with-chrono",
    "schema-sync",
    "entity-registry",
] }
uuid = { version = "1.23.0", features = ["v3", "v4"] }
log = "0.4.29"
env_logger = "0.11.10"
bon = "3.9.1"
mpris-server = "0.10.0"
zbus = "5.15.0"
async-trait = "0.1.89"

# We use these to parse the icomoon icons
[build-dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { package = "serde_json_path_to_error", version = "0.1.5" }

# Optimizes binary size
[profile.size]
inherits = "release"
codegen-units = 1
strip = true
lto = true
