[package]
name = "leidenfrost_backend"
version.workspace = true
authors.workspace = true
edition = "2024"

[dependencies]
sea-orm = { version = "2.0.0", features = [
    "sqlx-sqlite",
    "runtime-tokio",
    "with-chrono",
    "schema-sync",
    "entity-registry",
] }
http-serde = "2.1.1"
async-trait = "0.1.89"
directories = "6.0.0"
libmpv2 = "6.0.0"
env_logger = "0.11.11"
serde_json = { package = "serde_json_path_to_error", version = "0.1.5" }

tokio = { workspace = true, features = ["macros"] }
tokio-stream.workspace = true
console-subscriber = { workspace = true, optional = true }
serde.workspace = true
chrono.workspace = true
url.workspace = true
thiserror.workspace = true
color-eyre.workspace = true
reqwest.workspace = true
log.workspace = true
uuid.workspace = true

[dev-dependencies]
test_case = "3.3.1"

[features]
default = []
debug = ["tokio/tracing", "dep:console-subscriber"]
