// Auto-generated by build.rs
use iced::{
    Font,
    advanced::text,
    widget::{self, Text, text::Catalog},
};

pub fn trash<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f182}').font("leidenfrost")
}

pub fn spotify<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f0c4}').font("leidenfrost")
}

pub fn navidrome<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f000}').font("leidenfrost")
}

pub fn jellyfin<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f160}').font("leidenfrost")
}

pub fn image_down<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f4b7}').font("leidenfrost")
}

pub fn image_off<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f16a}').font("leidenfrost")
}

pub fn search<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f5ae}').font("leidenfrost")
}

pub fn x<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f44f}').font("leidenfrost")
}

pub fn heart_filled<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f002}').font("leidenfrost")
}

pub fn heart<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f001}').font("leidenfrost")
}

pub fn clock<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f004}').font("leidenfrost")
}

pub fn tag_filled<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f4cb}').font("leidenfrost")
}

pub fn tag<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f4ca}').font("leidenfrost")
}

pub fn user_filled<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f53c}').font("leidenfrost")
}

pub fn user<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f53b}').font("leidenfrost")
}

pub fn music<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f50d}').font("leidenfrost")
}

pub fn music_filled<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f50c}').font("leidenfrost")
}

pub fn disc_filled<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f5a1}').font("leidenfrost")
}

pub fn disc<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f5a0}').font("leidenfrost")
}

pub fn home_filled<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f515}').font("leidenfrost")
}

pub fn home<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f514}').font("leidenfrost")
}

pub fn settings_filled<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f3dd}').font("leidenfrost")
}

pub fn settings<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f3dc}').font("leidenfrost")
}

pub fn volume_x<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f0dc}').font("leidenfrost")
}

pub fn volume_two<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f5ac}').font("leidenfrost")
}

pub fn volume_one<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f551}').font("leidenfrost")
}

pub fn volume<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f395}').font("leidenfrost")
}

pub fn dices<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f0b0}').font("leidenfrost")
}

pub fn repeat_one<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f3be}').font("leidenfrost")
}

pub fn repeat<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f55c}').font("leidenfrost")
}

pub fn pause_filled<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f0be}').font("leidenfrost")
}

pub fn pause<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f0bd}').font("leidenfrost")
}

pub fn play_filled<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f255}').font("leidenfrost")
}

pub fn play<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f254}').font("leidenfrost")
}

pub fn skip_forward<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f398}').font("leidenfrost")
}

pub fn skip_forward_filled<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f397}').font("leidenfrost")
}

pub fn skip_back_filled<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f181}').font("leidenfrost")
}

pub fn skip_back<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f180}').font("leidenfrost")
}

pub fn shuffle<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f0ce}').font("leidenfrost")
}

pub fn square_filled<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f25d}').font("leidenfrost")
}

pub fn square<'a, Theme: Catalog + 'a, Renderer: text::Renderer<Font = Font>>() -> Text<'a, Theme, Renderer> {
    widget::text('\u{f25c}').font("leidenfrost")
}
